<inwork> permit pkg.json extra field extraction
Snyk/resolve-deps pull request #25
Opened 2016-10-22 00:37 UTC by cdaringe

# problem statement

- i need more fields from my package.json when doing dep reports than reported by default

# solution

- permit specifying `extraFields` 

# discussion

- please feel free to rename `extraFields` any way seen fit. not attached to the API name, just the functionality
- _great code_ guys.  seriously, excellent work.  very readable.  i was able to get in and get out no problem.  some API docs or doc blocks _could_ be handy, but thank you regardless :)

2016-10-22 01:16 UTC, cdaringe commented
alright, it took a couple tries, but we're all green.  node `0.10` support, killin' me!

2016-10-24 10:34 UTC, joshje requested changes
Nice PR! Just two minor changes to make for code consistency (see inline comments).

2016-10-24 10:34 UTC, joshje commented on lib/deps.js
> +      applyExtraFields(pkg, modules, options.extraFields)
Can we get a semicolon on the end of this line?

2016-10-24 10:34 UTC, joshje commented on lib/deps.js
> +          applyExtraFields(curr, acc[curr.name], options.extraFields)
Can we get a semicolon on the end of this line?

2016-10-24 16:19 UTC, cdaringe commented
tidied up!

2016-10-24 16:23 UTC, joshje approved these changes

2016-10-24 16:38 UTC, merged

2016-10-24 16:42 UTC, cdaringe commented
yahoo! 🎉 

what's your release process like?

2016-10-24 16:51 UTC, joshje commented
We merge this PR! https://github.com/Snyk/resolve-deps/pull/26 I'll do that now. 

It will kick off a travis build that will result in a new release. The version number will  be based off the commit messages, and will probably be `v1.8.0` in this case as it introduces a new feature.

2016-10-24 16:54 UTC, joshje commented
@cdaringe Congrats! https://github.com/Snyk/resolve-deps/releases/tag/v1.8.0 🎉

2016-10-25 18:21 UTC, cdaringe commented
thanks all!

On Mon, Oct 24, 2016 at 9:54 AM, Josh Emerson <notifications@github.com>
wrote:

> @cdaringe <https://github.com/cdaringe> Congrats! https://github.com/Snyk/
> resolve-deps/releases/tag/v1.8.0 🎉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Snyk/resolve-deps/pull/25#issuecomment-255798722>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA9O_XLgiGmZnFM3YCEVGnE5CjoWaoE_ks5q3OLigaJpZM4KdtKC>
> .
>